### ISSUE TITLE
Issue with fireworks in 1.19.3

### ISSUE THREAD

**Issue by Northy-017** [Myuuiii/EmpireWandPlus#108]
I use the plugin on a 1.19.3 paper server, but it seems whenever I use spells which involve fireworks, the firework entities (the rockets) shoot up and explode at a higher point than they should. I have tested this in a (1.19.3) paper server with just this plugin and the problem doesn't occur. Is this a problem with this plugin, or with plugins I have installed on the server?

**Comment by Myuuiii** [comment]
Hi there,
This used to be an issue in previous versions, currently we use a custom package to "spawn" fireworks with no flight duration, it could be that some other plugin is interfering with this one. 

I will look into it because I didn't update the plugin to 1.19.3 so it might be some compatibility issue.

On Monday I could test this, I'm very sorry that you are experiencing this issue. If everything goes well I could have time on Sunday, more updates to come!

**Comment by Northy-017** [comment]
Thanks so much for your quick response! I got the following error after using the wand on the server, perhaps this can help in the case!

> [11:57:47 ERROR]: Could not pass event PlayerInteractEvent to EmpireWandPlus v2.0.2
> java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.power" is null
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaFirework.getPower(CraftMetaFirework.java:392) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftFirework.setFireworkMeta(CraftFirework.java:66) ~[paper-1.19.3.jar:git-Paper-362]
        at com.myuuiii.empirewandplus.Spells.Spark.Spark.LaunchSpellFirework(Spark.java:31) ~[empirewandplus.jar:?]
        at com.myuuiii.empirewandplus.Abstracts.FireworksSpell.Execute(FireworksSpell.java:18) ~[empirewandplus.jar:?]
        at com.myuuiii.empirewandplus.Wands.WandMethods.ExecuteSpellOnLeftClick(WandMethods.java:47) ~[empirewandplus.jar:?]
        at com.myuuiii.empirewandplus.Wands.BloodWand.Handle(BloodWand.java:87) ~[empirewandplus.jar:?]
        at com.myuuiii.empirewandplus.Listeners.InteractionListener.onInteract(InteractionListener.java:17) ~[empirewandplus.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-362]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:493) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:489) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2606) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-362]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Myuuiii** [comment]
Hi again! I'm currently testing a build for 1.19.3, if that works, I'll be looking into releasing a 1.19.4 version

**Comment by Myuuiii** [comment]
From testing both 1.19.2 and 1.19.3 on my paper testing server I couldn't replicate the issue, I will release 2 new versions in a few minutes, one for 1.19.3 and one for 1.19.4. Please let me know if the issue persists

**Comment by Northy-017** [comment]
I've replaced the plugin with the newer file and tried the same, but unfortunately it seems that the issue still persists. I think it's an issue with another server-side plugin, especially seeing how the issue couldn't be replicated on your testing server.

I'll add the error message in the console, as well as the full list of our plugins below, perhaps they can help.

### CONSOLE ERROR
`[21:58:16 ERROR]: Could not pass event PlayerInteractEvent to EmpireWandPlus v2.1.0
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.power" is null
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaFirework.getPower(CraftMetaFirework.java:392) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftFirework.setFireworkMeta(CraftFirework.java:66) ~[paper-1.19.3.jar:git-Paper-362]
        at com.myuuiii.empirewandplus.Spells.Spark.EmpireSpark.LaunchSpellFirework(EmpireSpark.java:40) ~[EmpireWandPlus-2.1.0.jar:?]
        at com.myuuiii.empirewandplus.Abstracts.FireworksSpell.Execute(FireworksSpell.java:18) ~[EmpireWandPlus-2.1.0.jar:?]
        at com.myuuiii.empirewandplus.Wands.WandMethods.ExecuteSpellOnLeftClick(WandMethods.java:47) ~[EmpireWandPlus-2.1.0.jar:?]
        at com.myuuiii.empirewandplus.Wands.EmpireWand.Handle(EmpireWand.java:118) ~[EmpireWandPlus-2.1.0.jar:?]
        at com.myuuiii.empirewandplus.Listeners.InteractionListener.onInteract(InteractionListener.java:17) ~[EmpireWandPlus-2.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-362]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:493) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:489) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2606) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-362]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### SERVER PLUGIN LIST
AutoMessage-4.5.jar
CoreProtect-21.3.jar
Dynmap-3.5-beta-1-spigot.jar
Dynmap-WorldGuard-1.2.jar
EmpireWandPlus-2.1.0.jar
EssentialsX-2.19.7.jar
FastAsyncWorldEdit-Bukkit-2.5.1-SNAPSHOT-336.jar
floodgate-spigot.jar
Geyser-Spigot.jar
KingdomCraftStarter-6.12.2.jar
LibsDisguises-10.0.32-Free.jar
LuckPerms-Bukkit-5.4.62.jar
Morph-3.1.jar
ProtocolLib.jar
SaveIt.jar
Shopkeepers-2.16.5.jar
VanishNoPacket.jar
ViaBackwards-4.5.1.jar
ViaVersion-4.6.0.jar
Vivecraft_Spigot_Extensions.jar
worldguard-bukkit-7.0.8-beta-01-dist.jar

**Comment by Myuuiii** [comment]
Heya, I think it *might* have something to do with the ViaVersion/ViaBackwards plugin. Not completely sure but that does seem like one that could cause problems. When I have time i will try to download all the plugins and see where it gives the result you are getting. Until then you could maybe try and see if you can start the server without the backwards compatibility plugins maybe? I don't know if that's possible as I don't know how your server runs and such. I'll try to make work of it!

**Comment by Myuuiii** [comment]
oooh weird, I'll see when I have time to test it all, I'm sorry but I have a very busy schedule because of an internship. I'll try my best to get the testing done by the end of the week. Thank you for being patient with me!

**Comment by Northy-017** [comment]
Don't worry about it! We're in no rush. Good luck with your internship!

**Comment by Myuuiii** [comment]
Thank you! quick question, could you make a zip/tar of the plugins in your server (config isnt required) and upload it? just so I have the exact same plugins as you do :D

**Comment by Northy-017** [comment]
YO! I think you fixed it!!! The fireworks actually explode immediately now!

**Comment by Northy-017** [comment]
Do you still need a zip of all the server plugins?

**Comment by Myuuiii** [comment]
Woah okay, I'll make another version where I apply it to all the spells then! I'll send you that update soon! (maybe tomorrow morning/afternoon). If it seems to work then I won't need a zip of the plugins anymore

**Comment by Northy-017** [comment]
Thanks so much for your support man, I genuinely appreciate you!! Best dev on GitHub for real <3 :P

**Comment by Myuuiii** [comment]
Thank you man, that really means a lot! <3

**Comment by Myuuiii** [comment]
Here is a pre-release with the things changed. [View the pre-release](https://github.com/Myuuiii/EmpireWandPlus/releases/tag/2.1.1-pre)

**Comment by Northy-017** [comment]
DUDE thank you so much you're an absolute legend! Is there any way we can repay you?? You're a serious legend for doing all this for me <3

**Comment by Myuuiii** [comment]
Haha, man you even using my code already means the world to me! ♪(^∇^*)

**Comment by Myuuiii** [comment]
Do you have any confirmation that the latest version of the plugin (that I sent to you) resolved the issue? If so, I'll merge it into the main release :)

**Comment by Northy-017** [comment]
Apologies for my late response! But yes, everything is working accordingly.

**Comment by Myuuiii** [comment]
Hah no worries, just making sure before I push code that isn't working ;)

Thank you very much!
Let me know if I can mean anything for you or your server!
